### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by yudai-nkt** [yitzchak/ouroboros#138]
I'm currently reorganizing my dotfiles in a way more compliant to the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/latest/) to make my home directory less cluttered. [Many softwares](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support#Supported) including latexmk follow this specification and I'd be glad if DiCy joins the party.

In that case, `$XDG_CONFIG_HOME/dicy/dicy.yaml` will be read instead of `~/.dicy.yaml` (file name might be change at this point as the `dicy` subdirectory explicitly describes the YAML file is about DiCy). If `$XDG_CONFIG_HOME` is unset or empty, it should be replaced with `$HOME/.config`. The YAML file in user's home directory can still be used and whether or not to keep backward-compatibility is entirely up to you of course.

**Comment by yitzchak** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by yitzchak** [comment]
@yudai-nkt #139 should accomplish this. I'll merge it eventually, but it may be a while before it's released since I working on a large update.
