### ISSUE TITLE
Advantages of DiCy

### ISSUE THREAD

**Issue by yudai-nkt** [yitzchak/ouroboros#85]
(this isn't an issue report but a suggestion)

I got interested in DiCy after receiving area/language-latex#146, but I fail to clearly see the pros especially as a CLI tool. When used as a Node.js library like in `atom-latex`, DiCy makes a package more self-contained, but this isn't the case for CLI use.

Adding a small description of the advantages of DiCy (possibly comparisons with existing LaTeX automation tools like arara or latexmk) in `README.md` or GitHub Pages will make DiCy more attractive, I think. :smile:

**Comment by yitzchak** [comment]
Good point! Do you mind being a reviewer on the PR once I am done?

**Comment by yudai-nkt** [comment]
Of course not, but can I be a reviewer without an access to this repository?

**Comment by yitzchak** [comment]
Just a read through by someone else is the most helpful aspect. Plus anyone can comment on PRs even without the formal reviewer role.

**Comment by yudai-nkt** [comment]
I see. I'd give a proofread if I can be of any help!
